version: 0.3.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\VersionInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: Nuget packages