version: 0.2.0.{build}
branches:
  only:
  - master
skip_tags: true
assembly_info:
  patch: true
  file: '**\VersionInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: '**\Tobacco.dll'
  name: Assembly